[build]
  base = "client"
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://tish-production.up.railway.app/api/:splat"
  status = 200
  force = true
  headers = {Cache-Control = "no-cache"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
